name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry run (no actual publish)"
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org/"

      - name: Prepare platforms
        run: node scripts/prepare.js

      - name: Publish packages
        run: node scripts/publish.js ${{ github.event.inputs.dryRun && '--dry-run' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
